controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    articulation_controller:
      type: position_controllers/JointPositionController
      joint: articulation_joint

    left_wheels_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - front_left_drive_joint
        - rear_left_drive_joint

    right_wheels_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - front_right_drive_joint
        - rear_right_drive_joint
        
    velocity_controller:
			type: diff_drive_controller/DiffDriveController
			left_wheel_names: ["front_left_drive_joint", "rear_left_drive_joint"]
			right_wheel_names: ["front_right_drive_joint", "rear_right_drive_joint"]
			wheel_separation: ${base_width}  # Ширина рамы (из URDF)
			wheel_radius: ${wheel_radius}    # Радиус колеса (из URDF)
			odom_frame_id: odom
			base_frame_id: base_link
			publish_rate: 50
