controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    articulation_controller:
      type: position_controllers/JointPositionController
      joint: articulation_joint

    left_wheels_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - front_left_drive_joint
        - rear_left_drive_joint

    right_wheels_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - front_right_drive_joint
        - rear_right_drive_joint
